/* Real-browser integration checks. Uses an isolated Chrome profile and ephemeral local
 * origin so the developer's saved Administration data is never modified. */
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const root=path.resolve(__dirname,'../..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'nirvivad-admin-browser-'));
const chromePath=process.env.CHROME_BIN||'/usr/bin/google-chrome';
const wait=ms=>new Promise(r=>setTimeout(r,ms));let chrome,ws,origin,id=0,checks=0;const pending=new Map(),errors=[],failedRequests=[];
const server=http.createServer((req,res)=>{let file;try{file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));}catch{res.writeHead(400);return res.end();}if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');fs.readFile(file,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(b);});});
function send(method,params={}){return new Promise((resolve,reject)=>{const messageId=++id;pending.set(messageId,{resolve,reject});ws.send(JSON.stringify({id:messageId,method,params}));});}
async function evaluate(fn,arg=null){const result=await send('Runtime.evaluate',{expression:`(${fn.toString()})(${JSON.stringify(arg)})`,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;}
async function until(fn,description='condition'){for(let i=0;i<100;i++){if(await evaluate(fn))return;await wait(60);}throw Error('Timed out waiting for '+description);}
async function check(label,fn){assert.ok(await evaluate(fn),label);checks++;console.log('PASS '+label);}
async function route(hash){await evaluate(value=>{location.hash=value;},hash);await wait(100);await until(()=>!!document.querySelector('main h1'),'route '+hash);}
async function fill(formId,values){await evaluate(({formId,values})=>{const form=document.getElementById(formId);for(const [key,value]of Object.entries(values)){const input=form.elements.namedItem(key);if(!input)throw Error('Missing input '+key);if(input.type==='checkbox')input.checked=value;else input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}},{formId,values});}
async function submit(formId,intent){await evaluate(({formId,intent})=>{const form=document.getElementById(formId);const button=intent?Array.from(form.querySelectorAll('button[type=submit]')).find(b=>b.value===intent):form.querySelector('button[type=submit]');form.requestSubmit(button);},{formId,intent});await wait(120);}
async function click(selector){await evaluate(selector=>{const node=document.querySelector(selector);if(!node)throw Error('Missing element '+selector);node.click();},selector);await wait(80);}
async function confirm(){await click('[data-action=confirm]');}
async function login(email='sa@nirvivad.example',password='Nirvivad@123'){await fill('login-form',{email,password});await submit('login-form');await until(()=>!!document.querySelector('.admin-shell'),'sign in');}
async function screenshot(name){await evaluate(()=>{scrollTo({top:0,behavior:'instant'});document.activeElement.blur();document.getElementById('toast').hidden=true;});await wait(120);const shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(temp,name+'.png'),Buffer.from(shot.data,'base64'));}
async function logout(){await click('[data-action=logout]');await until(()=>!!document.querySelector('#login-form'),'sign out');}
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;
 chrome=spawn(chromePath,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--no-first-run','--remote-debugging-port=0','--user-data-dir='+path.join(temp,'chrome'),'about:blank'],{stdio:'ignore'});
 const activePort=path.join(temp,'chrome','DevToolsActivePort');for(let i=0;i<100&&!fs.existsSync(activePort);i++)await wait(100);if(!fs.existsSync(activePort))throw Error('Chrome did not start. Set CHROME_BIN if needed.');const port=fs.readFileSync(activePort,'utf8').split('\n')[0];
 const tabs=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(resolve=>ws.addEventListener('open',resolve,{once:true}));
 ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);else if(m.method==='Network.responseReceived'&&m.params.response.status>=400)failedRequests.push(m.params.response.url);});
 await send('Runtime.enable');await send('Network.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await send('Page.navigate',{url:origin+'/admin/'});await until(()=>!!document.querySelector('#login-form'),'initial seed and login');await screenshot('login-desktop');
 await fill('login-form',{email:'sa@nirvivad.example',password:'WrongPassword@123'});await submit('login-form');await until(()=>!document.getElementById('form-error').hidden,'invalid credentials error');await check('Wrong password is rejected',()=>document.getElementById('form-error').textContent.includes('incorrect'));
 await login();await screenshot('overview-desktop');
 await check('Source master entries and subscription limits seeded',()=>Object.values(AdminStore.getState().masters).flat().length===58&&AdminStore.listPlans().map(p=>p.propertyLimit).join(',')==='1,5');await route('prototype-summary');await check('Prototype summary records major journeys',()=>{const text=document.querySelector('main').textContent;return ['Account entry & roles','KYC & professional approval','Property Owner journey','Buyer enquiry journey','Current prototype boundaries'].every(x=>text.includes(x))&&!!document.querySelector('.sidebar a[href="#prototype-summary"]')});
 const routes=['overview','prototype-summary','users','users?view=hierarchy','user?id=user-2','user-edit','user-edit?id=user-3','permissions?id=user-3','masters?kind=land','masters?kind=building','masters?kind=city','masters?kind=ownership','masters?kind=dispute','masters?kind=unit','master-edit?kind=land','plans','plan?id=plan-1','plan-edit?id=plan-1','cms','cms-edit?slug=terms','cms-preview?slug=terms','profile','profile-edit','password'];
 for(const width of [1440,390]){
  await send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:width<700});
  for(const value of routes){await route(value);assert.ok(await evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+width+' '+value);assert.ok(await evaluate(()=>!document.querySelector('main h1').textContent.includes('available')),'Unavailable '+value);}
  checks+=routes.length;console.log(`PASS ${routes.length} Administration routes render without overflow at ${width}px`);
  await route('users');await screenshot('users-'+width);await route('cms-edit?slug=terms');await screenshot('cms-'+width);
 }
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await route('user-edit');await fill('user-form',{name:'Test Manager',email:'test.manager@example.com',role:'subadmin',managerId:'user-1',password:'ManagerTest@123',alsoEmployee:true});await submit('user-form');await until(()=>location.hash.startsWith('#user?id='),'new manager');
 await evaluate(()=>{window.testManagerId=new URLSearchParams(location.hash.split('?')[1]).get('id');});
 await check('Sub Admin created with Employee capability',()=>AdminStore.getUser(window.testManagerId).alsoEmployee===true);
 await route('user-edit');const managerId=await evaluate(()=>window.testManagerId);await fill('user-form',{name:'Test Employee',email:'test.employee@example.com',role:'employee',managerId,password:'EmployeeTest@123'});await submit('user-form');await until(()=>location.hash.startsWith('#user?id='),'new employee');await evaluate(()=>{window.testEmployeeId=new URLSearchParams(location.hash.split('?')[1]).get('id');});
 await check('Employee saved under selected manager',()=>AdminStore.getUser(window.testEmployeeId).managerId===window.testManagerId);
 await route('user?id='+managerId);await click('[data-action=user-status]');await confirm();await check('Manager deactivation blocked while reports exist',()=>document.getElementById('toast').textContent.includes('Reassign')&&AdminStore.getUser(window.testManagerId).active);
 const employeeId=await evaluate(()=>window.testEmployeeId);await route('user-edit?id='+employeeId);await fill('user-form',{managerId:'user-2',name:'Updated Test Employee'});await submit('user-form');await until(()=>location.hash.startsWith('#user?id='),'employee reassignment');
 await check('User edits and reassignment persist',()=>AdminStore.getUser(window.testEmployeeId).managerId==='user-2'&&AdminStore.getUser(window.testEmployeeId).name==='Updated Test Employee');
 await route('user?id='+managerId);await click('[data-action=user-status]');await confirm();await check('Manager can deactivate after reassignment',()=>!AdminStore.getUser(window.testManagerId).active);
 await click('[data-action=user-status]');await confirm();await click('[data-action=user-delete]');await confirm();await until(()=>location.hash==='#users','delete manager');await check('User deletion removes record',()=>!AdminStore.listUsers().some(u=>u.id===window.testManagerId));
 await route('permissions?id=user-3');await fill('permissions-form',{'perm:land:create':'allow','perm:land:edit':'allow','perm:subscriptions:edit':'allow'});await submit('permissions-form');await until(()=>location.hash.startsWith('#user?id='),'permissions saved');
 await route('master-edit?kind=land');await fill('master-form',{name:'Test land category',code:'TEST_LAND',sortOrder:'60',description:'A testing category.'});await submit('master-form');await until(()=>location.hash.startsWith('#masters'),'master created');
 await check('Master CRUD creation persists',()=>AdminStore.listMaster('land').some(m=>m.code==='TEST_LAND'));
 const masterId=await evaluate(()=>AdminStore.listMaster('land').find(m=>m.code==='TEST_LAND').id);
 await route('master-edit?kind=land&id='+masterId);await fill('master-form',{description:'Updated description'});await submit('master-form');await until(()=>location.hash.startsWith('#masters'),'master edit');
 await evaluate(()=>{document.querySelector('#list-search').value='TEST_LAND';document.querySelector('#list-search').dispatchEvent(new Event('input',{bubbles:true}));});await click('[data-action=master-status]');await confirm();await check('Master status changes persist',()=>!AdminStore.listMaster('land').find(m=>m.code==='TEST_LAND').active);await click('[data-action=master-delete]');await confirm();await check('Master delete removes value',()=>!AdminStore.listMaster('land').some(m=>m.code==='TEST_LAND'));
 await route('plan?id=plan-1');await click('[data-action=plan-status]');await confirm();await check('Unpriced workbook plan cannot activate',()=>document.getElementById('toast').textContent.includes('Configure a price')&&!AdminStore.listPlans()[0].active);
 await route('plan-edit?id=plan-1');await fill('plan-form',{price:'4999',active:true});await submit('plan-form');await until(()=>location.hash.startsWith('#plan?id='),'plan saved');await check('Configured subscription can activate',()=>AdminStore.listPlans()[0].active&&AdminStore.listPlans()[0].price===4999);
 await route('plan-edit');await fill('plan-form',{name:'Test annual plan',code:'TEST_PLAN',durationMonths:'12',propertyLimit:'3',price:'999',active:false});await submit('plan-form');await until(()=>location.hash.startsWith('#plan?id='),'plan created');await click('[data-action=plan-delete]');await confirm();await until(()=>location.hash==='#plans','plan deleted');await check('Plan creation and deletion work',()=>AdminStore.listPlans().length===2);
 await route('profile-edit');await fill('profile-form',{name:'Ananya Preview',phone:'+91 98765 43210'});await submit('profile-form');await until(()=>location.hash==='#profile','profile saved');await check('Profile edits persist without changing role',()=>AdminStore.currentUser().name==='Ananya Preview'&&AdminStore.currentUser().role==='superadmin');
 await route('cms-edit?slug=terms');await fill('cms-form',{title:'Approved terms preview'});await evaluate(()=>{document.querySelector('#cms-editor').innerHTML='<h2>Approved heading</h2><p>Published policy preview.</p><img src=x onerror="window.badCms=true"><a href="javascript:alert(1)">Unsafe link</a>';document.querySelector('#cms-editor').dispatchEvent(new Event('input',{bubbles:true}));});await submit('cms-form','published');await until(()=>location.hash==='#cms','CMS publish');
 await check('Published CMS HTML is sanitised',()=>!JSON.parse(localStorage.getItem('nirvivad-public-cms-v1')).terms.content.includes('onerror')&&!JSON.parse(localStorage.getItem('nirvivad-public-cms-v1')).terms.content.includes('javascript:'));
 await route('cms-edit?slug=terms');await evaluate(()=>{document.querySelector('#cms-editor').innerHTML='<p>Unpublished new draft.</p>';document.querySelector('#cms-editor').dispatchEvent(new Event('input',{bubbles:true}));});await submit('cms-form','draft');await until(()=>location.hash==='#cms','draft saved');await check('Draft preserves published policy',()=>JSON.parse(localStorage.getItem('nirvivad-public-cms-v1')).terms.content.includes('Published policy preview.'));
 await send('Page.navigate',{url:origin+'/#terms'});await until(()=>!!document.querySelector('.cms-published-content'),'public CMS policy');await check('Public policy page reads published CMS version',()=>document.querySelector('main h1').textContent==='Approved terms preview'&&document.querySelector('.cms-published-content').textContent.includes('Published policy preview.'));
 await send('Page.navigate',{url:origin+'/admin/'});await until(()=>!!document.querySelector('.admin-shell'),'persisted session');await logout();await login('subadmin@nirvivad.example');await route('users');await check('Sub Admin sees only their assigned Employees',()=>AdminStore.listUsers().every(u=>u.managerId==='user-2')&&!document.querySelector('#listing-content').textContent.includes('Arjun Patel'));
 await route('user?id=user-5');await check('Cross-team user deep link is denied',()=>document.querySelector('main h1').textContent.includes('available'));
 await route('cms');await check('Sub Admin CMS deep link denied',()=>document.querySelector('main h1').textContent.includes('available'));
 await route('plans');await check('Sub Admin subscriptions view only by default',()=>!document.querySelector('a[href="#plan-edit"]')&&!AdminStore.can('subscriptions','edit'));
 await logout();await login('employee@nirvivad.example');await check('Employee has no user-management navigation',()=>!document.querySelector('.sidebar a[href="#users"]'));
 await route('masters?kind=land');await check('Employee receives assigned master permissions',()=>!!document.querySelector('a[href="#master-edit?kind=land"]'));
 await route('masters?kind=building');await check('Unassigned master permissions remain view-only',()=>!document.querySelector('a[href="#master-edit?kind=building"]'));
 await route('plan-edit?id=plan-1');await check('Delegated edit cannot change plan status',()=>document.getElementById('field-active').disabled);await fill('plan-form',{description:'Edited by an authorised Employee.'});await submit('plan-form');await until(()=>location.hash.startsWith('#plan?id='),'delegated plan edit');await check('Delegated edit preserves active status',()=>AdminStore.listPlans()[0].active);
 await route('password');await fill('password-form',{currentPassword:'Nirvivad@123',newPassword:'NewEmployee@456',confirmPassword:'Mismatch@456'});await submit('password-form');await check('Password mismatch is rejected',()=>!document.getElementById('form-error').hidden);
 await fill('password-form',{confirmPassword:'NewEmployee@456'});await submit('password-form');await until(()=>!!document.querySelector('#login-form'),'password reauthentication');await login('employee@nirvivad.example','NewEmployee@456');await check('New password signs in',()=>AdminStore.currentUser().role==='employee');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await click('[data-action=menu]');await check('Mobile navigation opens',()=>document.body.classList.contains('sidebar-open'));await click('.sidebar a[href="#profile"]');await wait(120);await check('Mobile navigation closes after routing',()=>!document.body.classList.contains('sidebar-open'));await screenshot('employee-mobile');
 assert.equal(errors.length,0,'Runtime exceptions: '+JSON.stringify(errors));
 // The deliberate malicious-image sanitizer probe may request /admin/x before saving.
 const unexpected=failedRequests.filter(url=>!url.endsWith('/admin/x'));
 assert.equal(unexpected.length,0,'Unexpected failed requests '+JSON.stringify(unexpected));
 console.log(`Completed ${checks} checks. Screenshots: ${temp}`);fs.writeFileSync(path.join(temp,'results.json'),JSON.stringify({checks,errors,failedRequests},null,2));
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{if(ws)ws.close();if(chrome)chrome.kill();server.close();console.log('Artifacts: '+temp);setTimeout(()=>process.exit(process.exitCode||0),500);});
