/* Real-browser integration checks. Uses an isolated Chrome profile and ephemeral local
 * origin so the developer's saved Administration data is never modified. */
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const root=path.resolve(__dirname,'../..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'nirvivad-journey-browser-'));
const chromePath=process.env.CHROME_BIN||'/usr/bin/google-chrome';
const wait=ms=>new Promise(r=>setTimeout(r,ms));let chrome,ws,origin,id=0,checks=0;const pending=new Map(),errors=[],failedRequests=[];
const server=http.createServer((req,res)=>{let file;try{file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));}catch{res.writeHead(400);return res.end();}if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');fs.readFile(file,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(b);});});
function send(method,params={}){return new Promise((resolve,reject)=>{const messageId=++id;pending.set(messageId,{resolve,reject});ws.send(JSON.stringify({id:messageId,method,params}));});}
async function evaluate(fn,arg=null){const result=await send('Runtime.evaluate',{expression:`(${fn.toString()})(${JSON.stringify(arg)})`,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;}
async function until(fn,description='condition'){for(let i=0;i<100;i++){if(await evaluate(fn))return;await wait(60);}throw Error('Timed out waiting for '+description);}
async function check(label,fn){assert.ok(await evaluate(fn),label);checks++;console.log('PASS '+label);}
async function route(hash){await evaluate(value=>{location.hash=value;},hash);await wait(100);await until(()=>!!document.querySelector('main h1'),'route '+hash);}
async function fill(formId,values){await evaluate(({formId,values})=>{const form=document.getElementById(formId);for(const [key,value]of Object.entries(values)){const input=form.elements.namedItem(key);if(!input)throw Error('Missing input '+key);if(input.type==='checkbox')input.checked=value;else input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}},{formId,values});}
async function submit(formId,intent){await evaluate(({formId,intent})=>{const form=document.getElementById(formId);const button=intent?Array.from(form.querySelectorAll('button[type=submit]')).find(b=>b.value===intent):form.querySelector('button[type=submit]');form.requestSubmit(button);},{formId,intent});await wait(120);}
async function click(selector){await evaluate(selector=>{const node=document.querySelector(selector);if(!node)throw Error('Missing element '+selector);node.click();},selector);await wait(80);}
async function confirm(){await click('[data-action=confirm]');}
async function login(email='sa@nirvivad.example',password='Nirvivad@123'){await fill('login-form',{email,password});await submit('login-form');await until(()=>!!document.querySelector('.admin-shell'),'sign in');}
async function screenshot(name){await evaluate(()=>{scrollTo({top:0,behavior:'instant'});document.activeElement.blur();document.getElementById('toast').hidden=true;});await wait(120);const shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(temp,name+'.png'),Buffer.from(shot.data,'base64'));}
async function logout(){await click('[data-action=logout]');await until(()=>!!document.querySelector('#login-form'),'sign out');}
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;
 chrome=spawn(chromePath,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--no-first-run','--remote-debugging-port=0','--user-data-dir='+path.join(temp,'chrome'),'about:blank'],{stdio:'ignore'});
 const activePort=path.join(temp,'chrome','DevToolsActivePort');for(let i=0;i<100&&!fs.existsSync(activePort);i++)await wait(100);if(!fs.existsSync(activePort))throw Error('Chrome did not start');const port=fs.readFileSync(activePort,'utf8').split('\n')[0];
 const tabs=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(resolve=>ws.addEventListener('open',resolve,{once:true}));
 ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);else if(m.method==='Network.responseReceived'&&m.params.response.status>=400)failedRequests.push(m.params.response.url);});
 await send('Runtime.enable');await send('Network.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
 await send('Page.navigate',{url:origin+'/#properties'});await until(()=>!!document.querySelector('main h1'),'public site');await check('Anonymous public page has no property details or results',()=>!document.querySelector('.property-card,.property-grid,.results-grid')&&document.querySelector('main').textContent.includes('only after login'));await screenshot('public-gate');
 await send('Page.navigate',{url:origin+'/user/'});await until(()=>!!document.querySelector('#mobile-form'),'mobile sign in');await fill('mobile-form',{mobile:'9000000001'});await submit('mobile-form');await until(()=>!!document.querySelector('#otp-form'),'OTP screen');await fill('otp-form',{code:'123456'});await submit('otp-form');await until(()=>!!document.querySelector('#profile-form'),'profile screen');await fill('profile-form',{name:'Test Owner',email:'owner@example.test'});await submit('profile-form');await until(()=>!!document.querySelector('[data-role=owner]'),'role choice');await click('[data-role=owner]');await until(()=>location.hash==='#owner','owner dashboard');
 await route('property');await fill('property-form',{title:'Prototype house'});await submit('property-form','draft');await until(()=>location.hash==='#owner','draft dashboard');await check('Draft visible to owner',()=>document.querySelector('main').textContent.includes('Draft')&&NirvivadJourney.listMine().length===1);
 const draft=await evaluate(()=>NirvivadJourney.listMine()[0].id);await route('property?id='+draft);await fill('property-form',{category:'Residential',state:'Maharashtra',location:'Pune',area:'1200',unit:'Square Foot',ownershipType:'Single Ownership'});await submit('property-form','submit');await until(()=>location.hash.startsWith('#owner-detail'),'submitted property');await check('Submitted property enters staff queue',()=>NirvivadJourney.listMine()[0].status==='submitted'&&NirvivadJourney.adminList({id:'sa',role:'superadmin',active:true},'property').some(p=>p.id===NirvivadJourney.listMine()[0].id));
 await send('Page.navigate',{url:origin+'/admin/'});await until(()=>!!document.querySelector('#login-form'),'staff login');await login();await route('requests?kind=property');await check('Admin property queue receives submitted property',()=>document.querySelector('main').textContent.includes('Prototype house'));await route('request?kind=property&id='+draft);await fill('request-form',{subAdminId:'user-2',employeeId:'',status:'under_review',remark:'Internal note',request:'Please provide more information'});await submit('request-form');await until(()=>!!document.querySelector('#request-form'),'request update');await check('Internal note saved',()=>NirvivadJourney.adminDetail(AdminStore.currentUser(),'property',location.hash.split('id=')[1]).internalRemarks.length===1);
 await route('request?kind=property&id='+draft);await fill('request-form',{employeeId:'user-3',status:'under_review'});await submit('request-form');await until(()=>!!document.querySelector('#request-form'),'employee assignment');await check('Employee assigned from Sub Admin team',()=>NirvivadJourney.adminDetail(AdminStore.currentUser(),'property',location.hash.split('id=')[1]).employeeId==='user-3');
 await logout();await login('employee@nirvivad.example');await route('requests?kind=property');await check('Assigned Employee sees property queue',()=>document.querySelector('main').textContent.includes('Prototype house'));await route('request?kind=property&id='+draft);await fill('request-form',{status:'additional_info',followUp:'Called owner to discuss area',update:'Our team is reviewing your information.'});await submit('request-form');await until(()=>!!document.querySelector('#request-form'),'employee follow-up');await check('Employee follow-up saved',()=>NirvivadJourney.adminDetail(AdminStore.currentUser(),'property',location.hash.split('id=')[1]).followUps.length===1);
 await send('Page.navigate',{url:origin+'/user/#owner-detail?id='+draft});await until(()=>!!document.querySelector('main h1'),'owner tracking');await check('Owner sees request but no internal note',()=>document.querySelector('main').textContent.includes('Please provide more information')&&!document.querySelector('main').textContent.includes('Internal note'));
 await route('roles');await click('[data-role=buyer]');await until(()=>location.hash==='#buyer','buyer dashboard');await route('browse');await check('Authenticated buyer sees limited listings',()=>document.querySelectorAll('.catalog-card').length===2&&!document.querySelector('main').textContent.includes('owner@example.test'));await route('enquiry?id=NV-DEMO-101');await fill('enquiry-form',{interestType:'Invest',message:'Please contact me about this property'});await submit('enquiry-form');await until(()=>location.hash.startsWith('#buyer-detail'),'buyer enquiry');await check('Buyer enquiry saved',()=>NirvivadJourney.myEnquiries().length===1);
 for(const width of [1440,390]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<700});for(const page of ['owner','buyer','browse','roles','property','enquiry?id=NV-DEMO-101']){await route(page);assert.ok(await evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+width+' '+page);checks++;}await screenshot('buyer-'+width)}
 await send('Page.navigate',{url:origin+'/admin/'});await until(()=>!!document.querySelector('.admin-shell'),'staff session');await logout();await login();await route('requests?kind=enquiry');await check('Admin buyer queue receives interest',()=>document.querySelector('main').textContent.includes('ENQ-')&&NirvivadJourney.adminList(AdminStore.currentUser(),'enquiry').length===1);
 assert.equal(errors.length,0,'Runtime exceptions: '+JSON.stringify(errors));assert.equal(failedRequests.length,0,'Failed requests '+JSON.stringify(failedRequests));console.log(`Completed ${checks} checks. Screenshots: ${temp}`);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{if(ws)ws.close();if(chrome)chrome.kill();server.close();console.log('Artifacts: '+temp);setTimeout(()=>process.exit(process.exitCode||0),500);});
